controller_list:
  - name: fake_xarm_controller
    type: $(arg fake_execution_type)
    joints:
      - xarm_6_joint
      - xarm_5_joint
      - xarm_4_joint
      - xarm_3_joint
      - xarm_2_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - xarm_1_joint
initial:  # Define initial robot poses per group
  - group: xarm
    pose: Up