controller_list:
  - name: fake_xarm_controller
    joints:
      - xarm_6_joint
      - xarm_5_joint
      - xarm_4_joint
      - xarm_3_joint
      - xarm_2_joint
  - name: fake_gripper_controller
    joints:
      - xarm_1_joint      
      - xarm_tip1_joint      
      - xarm_tip2_joint      
