xarm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - xarm_6_joint
    - xarm_5_joint
    - xarm_4_joint
    - xarm_3_joint
    - xarm_2_joint
  gains:
    xarm_6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    xarm_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    xarm_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    xarm_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    xarm_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1