# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: xarm
  joint_model_group_pose: Up
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - xarm_6_joint
    - xarm_5_joint
    - xarm_4_joint
    - xarm_3_joint
    - xarm_2_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /xarm/controller/trajectory
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - xarm_6_joint
      - xarm_5_joint
      - xarm_4_joint
      - xarm_3_joint
      - xarm_2_joint

# The gripper will not be used for now
#  - name: /xarm/controller/gripper
#    action_ns: gripper_cmd
#    type: GripperCommand
#    default: true
#    parallel: false
#    joints:
#      - xarm_1_joint
    